### ISSUE TITLE
Building without package-lock.json (ie. with Yarn) fails

### ISSUE THREAD

**Issue by CallumHoward** [michaelwooley/storybook-experimental-vite#10]
Hi, thanks for putting this repo together, having all these working together is really nice!

What I observed was, I initially tried installing with `yarn` rather than `npm`. This of course bypasses the `package-lock.json` which is checked in to the repo. It turns out this didn't work.

I then tried `npm i` exactly as per the instructions in the readme, and that worked fine.
I then tried deleting `package-lock.json` and `node_modules` and then doing `npm i` once again, and saw the same errors as with `yarn`.

I guess one of the dependencies has been updated with a change that breaks the `$app/env` mocking? I have no idea how to narrow it down though.

One other thing I tried was converting the `package-lock.json` to a `yarn.lock`:
```bash
yarn import
yarn add @sveltejs/kit  # to have `svelte-kit sync` command
yarn
git checkout package.json. # to reset svelte-kit to the version in `yarn.lock`
yarn
```
It gave the same errors.

Here are the errors in question:
<img width="1524" alt="Screen Shot 2022-07-24 at 9 35 56 am" src="https://user-images.githubusercontent.com/7144420/180626353-1c7143c7-ff45-43ba-bd0a-94bc0a090144.png">
<img width="1788" alt="Screen Shot 2022-07-24 at 9 41 30 am" src="https://user-images.githubusercontent.com/7144420/180626354-c7a16bd7-0e59-4cc2-acb9-55ab36359781.png">

**Comment by benmccann** [comment]
SvelteKit removed those variables. You can as well: https://github.com/michaelwooley/storybook-experimental-vite/commit/a7863406cd1b46a64043573fdaa732d7dfcffa0d

**Comment by CallumHoward** [comment]
Nice, everything works now. Thank you!
